name: Sync Fork

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: https://github.com/fullstack-hy2020/fullstack-hy2020.github.io
          upstream_branch: master
          downstream_branch: master
          token: ${{ secretes.GITHUB_TOKEN }}
          
